"""
SQLAlchemy ORM models for the Fair Lending AI Validation system.
"""

from sqlalchemy import Column, Integer, String, Float, Boolean, DateTime, Text, ForeignKey, JSON, Enum as SQLEnum
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from datetime import datetime
import enum

from app.database import Base


class TestDimension(str, enum.Enum):
    """Bias test dimensions."""
    GEOGRAPHIC = "geographic"
    INCOME = "income"
    GENDER = "gender"
    CREDIT = "credit"
    EDGE_CASES = "edge_cases"


class ScoringType(str, enum.Enum):
    """Scoring model types."""
    FAIR = "fair"
    BIASED = "biased"


class SeverityLevel(str, enum.Enum):
    """Bias severity levels."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class StudentProfile(Base):
    """
    Synthetic student profile generated by GenAI.
    """
    __tablename__ = "student_profiles"
    
    id = Column(Integer, primary_key=True, index=True)
    profile_id = Column(String(100), unique=True, index=True, nullable=False)
    
    # Personal Information
    name = Column(String(200), nullable=False)
    postcode = Column(String(10), nullable=False)
    region = Column(String(50), nullable=False)  # urban_tier1, rural_tier2, etc.
    state = Column(String(50), nullable=False)
    
    # Financial Information
    family_income = Column(Integer, nullable=False)  # in rupees
    cibil_score = Column(Integer, nullable=False)  # 300-900
    requested_loan_amount = Column(Integer, nullable=False)  # in rupees
    
    # Academic Information
    gpa = Column(Float, nullable=False)  # 0.0-10.0 (Indian 10-point scale)
    course = Column(String(100), nullable=False)
    educational_background = Column(String(100), nullable=False)
    college_tier = Column(String(50), nullable=True)  # tier1, tier2, tier3 (IITs/IIMs = tier1, top private = tier2, others = tier3)
    university_name = Column(String(200), nullable=True)  # Name of the college/university
    
    # Family Structure
    co_applicant = Column(String(50), nullable=True)  # parent, sibling, spouse, none
    employment_type = Column(String(50), nullable=False)  # salaried, self-employed, government, student
    family_structure = Column(String(50), nullable=False)  # nuclear, joint, single_parent, widow
    
    # Test Dimension
    test_dimension = Column(SQLEnum(TestDimension), nullable=False, index=True)
    
    # Metadata
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    
    # Relationships
    scores = relationship("ScoringResult", back_populates="profile", cascade="all, delete-orphan")
    
    def __repr__(self):
        return f"<StudentProfile(id={self.id}, profile_id={self.profile_id}, name={self.name})>"


class ScoringResult(Base):
    """
    Scoring results for a student profile (fair or biased).
    """
    __tablename__ = "scoring_results"
    
    id = Column(Integer, primary_key=True, index=True)
    profile_id = Column(Integer, ForeignKey("student_profiles.id"), nullable=False, index=True)
    scoring_type = Column(SQLEnum(ScoringType), nullable=False, index=True)
    
    # Scoring Results
    score = Column(Float, nullable=False)  # 1-10
    approval_decision = Column(String(20), nullable=False)  # approve, conditional, reject
    interest_rate = Column(Float, nullable=False)  # 8-15%
    collateral_required = Column(Boolean, default=False, nullable=False)
    reasoning = Column(Text, nullable=True)
    
    # Raw GenAI Response
    raw_response = Column(JSON, nullable=True)
    
    # Metadata
    prompt_version = Column(String(50), nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    # Relationships
    profile = relationship("StudentProfile", back_populates="scores")
    
    def __repr__(self):
        return f"<ScoringResult(id={self.id}, profile_id={self.profile_id}, type={self.scoring_type}, score={self.score})>"


class BiasMetric(Base):
    """
    Calculated bias metrics for a test run.
    """
    __tablename__ = "bias_metrics"
    
    id = Column(Integer, primary_key=True, index=True)
    test_run_id = Column(String(100), index=True, nullable=False)
    dimension = Column(SQLEnum(TestDimension), nullable=False, index=True)
    
    # Metrics
    approval_parity = Column(Float, nullable=False)  # Group1_Approval / Group2_Approval
    interest_rate_disparity = Column(Float, nullable=False)  # |Rate1 - Rate2|
    collateral_gap = Column(Float, nullable=False)  # |Collateral1% - Collateral2%|
    edge_case_coverage = Column(Float, nullable=False)  # % edge cases handled
    overall_fairness_score = Column(Float, nullable=False)  # 1-100
    
    # Statistical Validation
    p_value = Column(Float, nullable=True)
    t_statistic = Column(Float, nullable=True)
    is_statistically_significant = Column(Boolean, default=False)
    confidence_interval_lower = Column(Float, nullable=True)
    confidence_interval_upper = Column(Float, nullable=True)
    
    # Severity
    severity = Column(SQLEnum(SeverityLevel), nullable=False, index=True)
    
    # Group Comparisons
    group1_name = Column(String(100), nullable=False)
    group2_name = Column(String(100), nullable=False)
    group1_approval_rate = Column(Float, nullable=False)
    group2_approval_rate = Column(Float, nullable=False)
    group1_interest_rate = Column(Float, nullable=False)
    group2_interest_rate = Column(Float, nullable=False)
    group1_collateral_pct = Column(Float, nullable=False)
    group2_collateral_pct = Column(Float, nullable=False)
    
    # Metadata
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    def __repr__(self):
        return f"<BiasMetric(id={self.id}, test_run_id={self.test_run_id}, dimension={self.dimension}, fairness={self.overall_fairness_score})>"


class HumanFeedback(Base):
    """
    Human-in-the-loop feedback for bias findings.
    """
    __tablename__ = "human_feedback"
    
    id = Column(Integer, primary_key=True, index=True)
    bias_metric_id = Column(Integer, ForeignKey("bias_metrics.id"), nullable=False, index=True)
    
    # Feedback
    is_discriminatory = Column(String(20), nullable=False)  # yes, no, partially
    root_cause_analysis = Column(Text, nullable=True)
    severity_rating = Column(Integer, nullable=False)  # 1-5
    suggested_mitigation = Column(Text, nullable=True)
    
    # Annotator Information
    annotator_name = Column(String(100), nullable=True)
    annotator_role = Column(String(50), nullable=True)  # loan_officer, consultant, etc.
    
    # Metadata
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    def __repr__(self):
        return f"<HumanFeedback(id={self.id}, bias_metric_id={self.bias_metric_id}, severity={self.severity_rating})>"


class MitigationResult(Base):
    """
    Results from iterative mitigation cycles.
    """
    __tablename__ = "mitigation_results"
    
    id = Column(Integer, primary_key=True, index=True)
    mitigation_run_id = Column(String(100), index=True, nullable=False)
    iteration_number = Column(Integer, nullable=False)
    
    # Prompt Information
    prompt_version = Column(String(50), nullable=False)
    prompt_text = Column(Text, nullable=False)
    prompt_changes = Column(Text, nullable=True)  # What changed from previous version
    
    # Before Metrics (from previous iteration)
    before_fairness_score = Column(Float, nullable=True)
    before_approval_parity = Column(Float, nullable=True)
    before_interest_gap = Column(Float, nullable=True)
    before_collateral_gap = Column(Float, nullable=True)
    
    # After Metrics (current iteration)
    after_fairness_score = Column(Float, nullable=False)
    after_approval_parity = Column(Float, nullable=False)
    after_interest_gap = Column(Float, nullable=False)
    after_collateral_gap = Column(Float, nullable=False)
    
    # Improvement
    improvement_percentage = Column(Float, nullable=False)
    target_achieved = Column(Boolean, default=False)
    
    # Human Feedback Used
    feedback_ids = Column(JSON, nullable=True)  # List of feedback IDs that influenced this iteration
    
    # Metadata
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    def __repr__(self):
        return f"<MitigationResult(id={self.id}, iteration={self.iteration_number}, improvement={self.improvement_percentage}%)>"


class TestRun(Base):
    """
    Tracks a complete test run (generation + scoring + metrics).
    """
    __tablename__ = "test_runs"
    
    id = Column(Integer, primary_key=True, index=True)
    test_run_id = Column(String(100), unique=True, index=True, nullable=False)
    
    # Test Configuration
    profile_count = Column(Integer, nullable=False)
    dimensions_tested = Column(JSON, nullable=False)  # List of dimensions
    
    # Status
    status = Column(String(50), nullable=False, default="pending")  # pending, generating, scoring, completed, failed
    progress_percentage = Column(Float, default=0.0)
    
    # Results Summary
    total_profiles_generated = Column(Integer, default=0)
    total_profiles_scored = Column(Integer, default=0)
    total_metrics_calculated = Column(Integer, default=0)
    
    # Error Information
    error_message = Column(Text, nullable=True)
    
    # Metadata
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    completed_at = Column(DateTime(timezone=True), nullable=True)
    
    def __repr__(self):
        return f"<TestRun(id={self.id}, test_run_id={self.test_run_id}, status={self.status})>"


class User(Base):
    """
    User account for authentication.
    """
    __tablename__ = "users"
    
    id = Column(Integer, primary_key=True, index=True)
    employee_id = Column(String(50), unique=True, index=True, nullable=False)
    password_hash = Column(String(255), nullable=False)  # Hashed password
    full_name = Column(String(200), nullable=False)
    email = Column(String(200), nullable=True)
    role = Column(String(50), default="analyst", nullable=False)  # analyst, admin, manager
    is_active = Column(Boolean, default=True, nullable=False)
    
    # Metadata
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    last_login = Column(DateTime(timezone=True), nullable=True)
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    
    def __repr__(self):
        return f"<User(id={self.id}, employee_id={self.employee_id}, role={self.role})>"



